create table if not exists public.high_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(btrim(player_name)) between 1 and 20),
  score integer not null check (score >= 0 and score <= 100000),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists high_scores_score_idx
  on public.high_scores (score desc, created_at asc);

alter table public.high_scores enable row level security;

drop policy if exists "Anyone can read high scores" on public.high_scores;
create policy "Anyone can read high scores"
  on public.high_scores for select
  to anon
  using (true);

drop policy if exists "Anyone can submit high scores" on public.high_scores;
create policy "Anyone can submit high scores"
  on public.high_scores for insert
  to anon
  with check (
    char_length(btrim(player_name)) between 1 and 20
    and score between 0 and 100000
  );
